In [1]:
import pandas as pd
!pip install tensorflow==2.21.0 keras==3.12.1

Collecting tensorflow==2.21.0
  Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
Collecting keras==3.12.1
  Downloading keras-3.12.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (26.1)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow==2.21.0)
  Downloading protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (1.80.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (2.0.2)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow==2.21.0)
  Downloading h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow==2.21.0) (0.5.4)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras==3.12.1) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras==3.12.1) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras==3.12.1) (0.19.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow==2.21.0) (0.47.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow==2.21.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow==2.21.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow==2.21.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow==2.21.0) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras==3.12.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras==3.12.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras==3.12.1) (0.1.2)
Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl (572.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 MB 3.3 MB/s eta 0:00:00
Downloading keras-3.12.1-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 80.7 MB/s eta 0:00:00
Downloading h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 136.5 MB/s eta 0:00:00
Downloading protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.3/324.3 kB 30.2 MB/s eta 0:00:00
Installing collected packages: protobuf, h5py, keras, tensorflow
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: h5py
    Found existing installation: h5py 3.16.0
    Uninstalling h5py-3.16.0:
      Successfully uninstalled h5py-3.16.0
  Attempting uninstall: keras
    Found existing installation: keras 3.13.2
    Uninstalling keras-3.13.2:
      Successfully uninstalled keras-3.13.2
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.20.0
    Uninstalling tensorflow-2.20.0:
      Successfully uninstalled tensorflow-2.20.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-aiplatform 1.148.1 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.34.1 which is incompatible.
google-cloud-discoveryengine 0.13.12 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
tensorflow-text 2.20.1 requires tensorflow<2.21,>=2.20.0, but you have tensorflow 2.21.0 which is incompatible.
google-cloud-bigtable 2.36.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
ydf-tf 2.20.0 requires tensorflow==2.20.0, but you have tensorflow 2.21.0 which is incompatible.
tf-keras 2.20.0 requires tensorflow<2.21,>=2.20, but you have tensorflow 2.21.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 7.34.1 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.34.1 which is incompatible.
keras-hub 0.26.0 requires keras>=3.13, but you have keras 3.12.1 which is incompatible.
Successfully installed h5py-3.14.0 keras-3.12.1 protobuf-7.34.1 tensorflow-2.21.0

In [2]:
data=pd.read_json('News_Category_Dataset_v3.json',lines=True)

In [3]:
data.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

# Data Exploration

In [4]:
data.shape

(209527, 6)

In [5]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='object')

In [6]:
data= data['short_description'].sample(20000)

In [7]:
data

66208
145821    While a housemaid attempts to hurry along the ...
124652
55839        Sunday is Gold Star Mother's and Family's Day.
150749    There is the same gap when it comes to using p...
                                ...
158428    Whatever you are trying to achieve, I hope tha...
52049           These two might be headed to the courtroom.
192923    CORRECTION: A previous version of this article...
18124     A former campaign staffer and a lobbyist have ...
119476
Name: short_description, Length: 20000, dtype: object

# Data Cleaning

In [8]:
data.isnull().sum()

np.int64(0)

In [9]:
data.duplicated().sum()

np.int64(2023)

In [10]:
data.drop_duplicates(inplace=True)

# Tokenization

In [11]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [12]:
tokenizer = Tokenizer(oov_token='<OOV')

In [13]:
tokenizer.fit_on_texts(data)

In [14]:
tokenizer.word_index

{'<OOV': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'is': 8,
 'that': 9,
 'for': 10,
 'i': 11,
 'you': 12,
 'on': 13,
 'it': 14,
 'are': 15,
 'with': 16,
 'as': 17,
 'be': 18,
 'we': 19,
 'this': 20,
 'have': 21,
 'was': 22,
 'but': 23,
 'at': 24,
 'not': 25,
 'your': 26,
 'from': 27,
 'my': 28,
 'has': 29,
 'an': 30,
 'or': 31,
 'more': 32,
 'about': 33,
 'our': 34,
 'by': 35,
 'one': 36,
 'can': 37,
 'what': 38,
 'all': 39,
 'when': 40,
 'their': 41,
 'will': 42,
 'they': 43,
 'his': 44,
 'who': 45,
 'out': 46,
 "it's": 47,
 'if': 48,
 'he': 49,
 'new': 50,
 'just': 51,
 'up': 52,
 'time': 53,
 'people': 54,
 'her': 55,
 'like': 56,
 'so': 57,
 'do': 58,
 'some': 59,
 'there': 60,
 'how': 61,
 'been': 62,
 'said': 63,
 'no': 64,
 'than': 65,
 'us': 66,
 'me': 67,
 'life': 68,
 'many': 69,
 'most': 70,
 'day': 71,
 'get': 72,
 'year': 73,
 'had': 74,
 'she': 75,
 'over': 76,
 'after': 77,
 'these': 78,
 'make': 79,
 'into': 80,
 'were': 81,
 'would': 82,
 'want': 83,
 'first': 84,
 'may': 85,
 'know': 86,
 'years': 87,
 'even': 88,
 'now': 89,
 'them': 90,
 'its': 91,
 'world': 92,
 'other': 93,
 'only': 94,
 'way': 95,
 "don't": 96,
 'because': 97,
 'president': 98,
 'much': 99,
 'while': 100,
 'trump': 101,
 'love': 102,
 'could': 103,
 'which': 104,
 'see': 105,
 'two': 106,
 'last': 107,
 'take': 108,
 'also': 109,
 'those': 110,
 'here': 111,
 'being': 112,
 'good': 113,
 '”': 114,
 'best': 115,
 'back': 116,
 'need': 117,
 'think': 118,
 'say': 119,
 'should': 120,
 'look': 121,
 'week': 122,
 'really': 123,
 'women': 124,
 'still': 125,
 'where': 126,
 'go': 127,
 'old': 128,
 'right': 129,
 'every': 130,
 'never': 131,
 's': 132,
 'u': 133,
 'says': 134,
 'any': 135,
 'something': 136,
 'health': 137,
 'help': 138,
 'things': 139,
 'going': 140,
 'down': 141,
 'well': 142,
 'long': 143,
 'little': 144,
 'through': 145,
 'why': 146,
 'made': 147,
 'own': 148,
 'work': 149,
 'home': 150,
 'children': 151,
 'before': 152,
 'too': 153,
 'off': 154,
 'around': 155,
 'family': 156,
 'few': 157,
 "you're": 158,
 'great': 159,
 'change': 160,
 'find': 161,
 'very': 162,
 'kids': 163,
 'always': 164,
 'then': 165,
 "i'm": 166,
 'better': 167,
 'thing': 168,
 'state': 169,
 'check': 170,
 'did': 171,
 'come': 172,
 'often': 173,
 'him': 174,
 'big': 175,
 'news': 176,
 'feel': 177,
 'does': 178,
 'might': 179,
 'ever': 180,
 'donald': 181,
 'food': 182,
 'house': 183,
 'during': 184,
 'show': 185,
 'both': 186,
 'next': 187,
 'sure': 188,
 'days': 189,
 'part': 190,
 'whether': 191,
 'against': 192,
 'city': 193,
 "we're": 194,
 'school': 195,
 'comes': 196,
 'three': 197,
 'each': 198,
 'american': 199,
 'between': 200,
 'found': 201,
 'am': 202,
 'keep': 203,
 'another': 204,
 'without': 205,
 'since': 206,
 'got': 207,
 'same': 208,
 'care': 209,
 'white': 210,
 "that's": 211,
 'yet': 212,
 "can't": 213,
 'real': 214,
 'live': 215,
 'end': 216,
 'lives': 217,
 'parents': 218,
 'place': 219,
 'former': 220,
 'country': 221,
 'making': 222,
 'getting': 223,
 'night': 224,
 "there's": 225,
 'let': 226,
 'today': 227,
 "doesn't": 228,
 'high': 229,
 'child': 230,
 'twitter': 231,
 'again': 232,
 "didn't": 233,
 'man': 234,
 'huffpost': 235,
 "isn't": 236,
 'enough': 237,
 'lot': 238,
 'facebook': 239,
 'important': 240,
 'use': 241,
 'national': 242,
 'give': 243,
 'called': 244,
 'york': 245,
 'less': 246,
 'public': 247,
 'away': 248,
 'times': 249,
 'become': 250,
 'hard': 251,
 'black': 252,
 'such': 253,
 'put': 254,
 'different': 255,
 'past': 256,
 'wedding': 257,
 '1': 258,
 'told': 259,
 'friends': 260,
 'once': 261,
 'face': 262,
 'video': 263,
 'full': 264,
 'doing': 265,
 'having': 266,
 'looking': 267,
 'young': 268,
 'states': 269,
 'thought': 270,
 'read': 271,
 'free': 272,
 'ago': 273,
 'month': 274,
 'top': 275,
 'makes': 276,
 'social': 277,
 'story': 278,
 'party': 279,
 "i've": 280,
 'men': 281,
 'start': 282,
 'yourself': 283,
 'though': 284,
 'someone': 285,
 'recent': 286,
 'set': 287,
 'person': 288,
 'everyone': 289,
 'history': 290,
 'government': 291,
 'money': 292,
 'media': 293,
 'far': 294,
 'study': 295,
 'according': 296,
 'believe': 297,
 'must': 298,
 'experience': 299,
 'stop': 300,
 'police': 301,
 'season': 302,
 'others': 303,
 'million': 304,
 'easy': 305,
 'took': 306,
 'style': 307,
 'five': 308,
 'trying': 309,
 'summer': 310,
 '—': 311,
 'actually': 312,
 'heart': 313,
 'nothing': 314,
 'star': 315,
 'least': 316,
 'political': 317,
 'americans': 318,
 'america': 319,
 '10': 320,
 'moment': 321,
 'human': 322,
 'case': 323,
 'campaign': 324,
 'working': 325,
 'body': 326,
 'job': 327,
 'travel': 328,
 'favorite': 329,
 'ways': 330,
 'already': 331,
 'future': 332,
 'republican': 333,
 'fashion': 334,
 'divorce': 335,
 'age': 336,
 'below': 337,
 'talk': 338,
 'months': 339,
 'percent': 340,
 'community': 341,
 'taking': 342,
 'mind': 343,
 'tell': 344,
 'until': 345,
 'sometimes': 346,
 'used': 347,
 'lost': 348,
 'together': 349,
 '000': 350,
 'obama': 351,
 'try': 352,
 'matter': 353,
 'call': 354,
 'recently': 355,
 'power': 356,
 'move': 357,
 'across': 358,
 'point': 359,
 'everything': 360,
 'four': 361,
 'under': 362,
 'healthy': 363,
 "he's": 364,
 "we've": 365,
 'means': 366,
 'seems': 367,
 'mom': 368,
 'film': 369,
 'simple': 370,
 'known': 371,
 'baby': 372,
 'united': 373,
 'needs': 374,
 'bad': 375,
 'rights': 376,
 'remember': 377,
 'mean': 378,
 'happy': 379,
 'fact': 380,
 'post': 381,
 'latest': 382,
 'it’s': 383,
 'support': 384,
 'woman': 385,
 'perfect': 386,
 'self': 387,
 'sleep': 388,
 'left': 389,
 'hope': 390,
 'second': 391,
 'however': 392,
 'share': 393,
 'came': 394,
 'deal': 395,
 'wanted': 396,
 'idea': 397,
 'business': 398,
 'group': 399,
 'question': 400,
 'watch': 401,
 'fall': 402,
 "they're": 403,
 'photos': 404,
 'election': 405,
 'bill': 406,
 'climate': 407,
 'late': 408,
 'able': 409,
 'asked': 410,
 'maybe': 411,
 'six': 412,
 'kind': 413,
 'went': 414,
 'anything': 415,
 'based': 416,
 'seen': 417,
 'common': 418,
 'coming': 419,
 'bring': 420,
 'head': 421,
 'living': 422,
 '2': 423,
 'instead': 424,
 'daughter': 425,
 'system': 426,
 "you've": 427,
 'list': 428,
 'university': 429,
 'sense': 430,
 'likely': 431,
 'number': 432,
 'mother': 433,
 'research': 434,
 'company': 435,
 'learn': 436,
 'court': 437,
 'course': 438,
 'series': 439,
 'law': 440,
 'true': 441,
 'including': 442,
 'decision': 443,
 'problem': 444,
 'started': 445,
 'relationship': 446,
 'probably': 447,
 'death': 448,
 'especially': 449,
 'plan': 450,
 'wants': 451,
 'gay': 452,
 'issue': 453,
 'single': 454,
 'college': 455,
 'major': 456,
 'pretty': 457,
 'cancer': 458,
 'washington': 459,
 'early': 460,
 'com': 461,
 'anyone': 462,
 'stress': 463,
 'order': 464,
 'small': 465,
 'weekend': 466,
 'holiday': 467,
 'process': 468,
 "you'll": 469,
 'fun': 470,
 'words': 471,
 'possible': 472,
 'clinton': 473,
 'ask': 474,
 'general': 475,
 'myself': 476,
 'water': 477,
 'whole': 478,
 'war': 479,
 'run': 480,
 'gop': 481,
 'leave': 482,
 'hours': 483,
 'trip': 484,
 'done': 485,
 'bit': 486,
 'daily': 487,
 'wrong': 488,
 'turn': 489,
 'among': 490,
 'game': 491,
 'yes': 492,
 "trump's": 493,
 'spring': 494,
 "here's": 495,
 'issues': 496,
 'book': 497,
 "won't": 498,
 'open': 499,
 'don’t': 500,
 'marriage': 501,
 'line': 502,
 'seem': 503,
 'several': 504,
 'short': 505,
 'hit': 506,
 'host': 507,
 'art': 508,
 'sunday': 509,
 'morning': 510,
 'eat': 511,
 'looks': 512,
 'name': 513,
 'fear': 514,
 'air': 515,
 'presidential': 516,
 'control': 517,
 'tips': 518,
 'republicans': 519,
 'feeling': 520,
 'play': 521,
 '20': 522,
 'son': 523,
 'music': 524,
 'thinking': 525,
 'red': 526,
 'pinterest': 527,
 'personal': 528,
 'international': 529,
 'energy': 530,
 'special': 531,
 'action': 532,
 'federal': 533,
 'stay': 534,
 '5': 535,
 'nearly': 536,
 'justice': 537,
 '4': 538,
 'goes': 539,
 'eating': 540,
 'photo': 541,
 'almost': 542,
 'industry': 543,
 '3': 544,
 'online': 545,
 'democratic': 546,
 'behind': 547,
 'education': 548,
 'office': 549,
 'weeks': 550,
 "what's": 551,
 "she's": 552,
 'families': 553,
 'husband': 554,
 'reason': 555,
 'heard': 556,
 'ourselves': 557,
 '30': 558,
 'stories': 559,
 'act': 560,
 'finally': 561,
 'students': 562,
 'risk': 563,
 'create': 564,
 'rest': 565,
 'using': 566,
 'rather': 567,
 'wrote': 568,
 'sex': 569,
 'south': 570,
 'middle': 571,
 'practice': 572,
 'researchers': 573,
 'room': 574,
 'john': 575,
 'felt': 576,
 'saturday': 577,
 'shows': 578,
 'attention': 579,
 'local': 580,
 'pay': 581,
 'half': 582,
 'violence': 583,
 'friday': 584,
 'difficult': 585,
 'despite': 586,
 'reality': 587,
 'vote': 588,
 'sexual': 589,
 "let's": 590,
 'running': 591,
 'break': 592,
 'disease': 593,
 'movie': 594,
 'understand': 595,
 'win': 596,
 'upon': 597,
 'taken': 598,
 'california': 599,
 'questions': 600,
 'longer': 601,
 'focus': 602,
 'forward': 603,
 'beautiful': 604,
 'hand': 605,
 'key': 606,
 'continue': 607,
 'girl': 608,
 'ready': 609,
 'growing': 610,
 'truth': 611,
 'hear': 612,
 'simply': 613,
 'parent': 614,
 'street': 615,
 'killed': 616,
 'hot': 617,
 'role': 618,
 'level': 619,
 'lead': 620,
 'tax': 621,
 'friend': 622,
 'giving': 623,
 'beauty': 624,
 "wasn't": 625,
 'saying': 626,
 'given': 627,
 'term': 628,
 'girls': 629,
 'deep': 630,
 'moments': 631,
 'amazing': 632,
 'attack': 633,
 'positive': 634,
 'team': 635,
 'security': 636,
 'outside': 637,
 'strong': 638,
 'along': 639,
 'step': 640,
 'tuesday': 641,
 'winter': 642,
 'culture': 643,
 'center': 644,
 'takes': 645,
 'themselves': 646,
 'leaders': 647,
 'learned': 648,
 'couple': 649,
 'instagram': 650,
 'within': 651,
 'else': 652,
 'popular': 653,
 'record': 654,
 'race': 655,
 'society': 656,
 'spent': 657,
 "aren't": 658,
 'hillary': 659,
 'mental': 660,
 'career': 661,
 'weight': 662,
 'medical': 663,
 'global': 664,
 'front': 665,
 '“i': 666,
 'congress': 667,
 'above': 668,
 '7': 669,
 '2012': 670,
 'clear': 671,
 'side': 672,
 'shot': 673,
 'following': 674,
 'director': 675,
 'officials': 676,
 'gets': 677,
 'loss': 678,
 'space': 679,
 'nation': 680,
 'car': 681,
 'present': 682,
 'democrats': 683,
 "couldn't": 684,
 'challenge': 685,
 '2013': 686,
 'project': 687,
 'knows': 688,
 'companies': 689,
 'choice': 690,
 'senate': 691,
 'biggest': 692,
 'decades': 693,
 'hair': 694,
 'decided': 695,
 'needed': 696,
 'happen': 697,
 'countries': 698,
 'tv': 699,
 'truly': 700,
 'ones': 701,
 'sign': 702,
 'i’m': 703,
 'members': 704,
 'beyond': 705,
 'unique': 706,
 'close': 707,
 'color': 708,
 'perhaps': 709,
 'event': 710,
 '2014': 711,
 'tumblr': 712,
 'administration': 713,
 'alone': 714,
 'science': 715,
 'eyes': 716,
 'places': 717,
 'father': 718,
 'class': 719,
 'whatever': 720,
 'policy': 721,
 'department': 722,
 'response': 723,
 'became': 724,
 'fight': 725,
 'saw': 726,
 'opportunity': 727,
 'wife': 728,
 'inside': 729,
 'exactly': 730,
 'wear': 731,
 'information': 732,
 'financial': 733,
 'crisis': 734,
 'march': 735,
 '12': 736,
 'although': 737,
 'program': 738,
 'current': 739,
 'serious': 740,
 'word': 741,
 'offer': 742,
 'happens': 743,
 'hold': 744,
 'success': 745,
 'reasons': 746,
 'non': 747,
 'met': 748,
 'creative': 749,
 'safe': 750,
 'anti': 751,
 'secret': 752,
 'quite': 753,
 'reported': 754,
 'died': 755,
 'visit': 756,
 'finding': 757,
 'beach': 758,
 'married': 759,
 'data': 760,
 'powerful': 761,
 'd': 762,
 'knew': 763,
 'patients': 764,
 'created': 765,
 'held': 766,
 "wouldn't": 767,
 'report': 768,
 'touch': 769,
 'forget': 770,
 'meet': 771,
 'benefits': 772,
 'toward': 773,
 'dress': 774,
 'fans': 775,
 'north': 776,
 'politics': 777,
 'hate': 778,
 'seven': 779,
 'impact': 780,
 'service': 781,
 'natural': 782,
 'michael': 783,
 'internet': 784,
 'light': 785,
 'nominee': 786,
 'spend': 787,
 'dad': 788,
 'later': 789,
 'turned': 790,
 'advice': 791,
 'gun': 792,
 'technology': 793,
 'candidate': 794,
 'provide': 795,
 'born': 796,
 'adults': 797,
 'wednesday': 798,
 'click': 799,
 'relationships': 800,
 'legal': 801,
 'oh': 802,
 'ideas': 803,
 'buy': 804,
 'celebrate': 805,
 'communities': 806,
 'debate': 807,
 'view': 808,
 'soon': 809,
 'dead': 810,
 'avoid': 811,
 'boy': 812,
 'talking': 813,
 'enjoy': 814,
 'cannot': 815,
 'christmas': 816,
 'claims': 817,
 'choose': 818,
 'senator': 819,
 'attorney': 820,
 'began': 821,
 'modern': 822,
 'worst': 823,
 'himself': 824,
 'schools': 825,
 'experts': 826,
 'welcome': 827,
 'minutes': 828,
 'announced': 829,
 'expected': 830,
 'peace': 831,
 "i'd": 832,
 'road': 833,
 'drug': 834,
 'worse': 835,
 'walk': 836,
 'nature': 837,
 'learning': 838,
 'cut': 839,
 'economy': 840,
 'kid': 841,
 'lgbt': 842,
 'thousands': 843,
 'caught': 844,
 'interview': 845,
 'san': 846,
 'potential': 847,
 'wait': 848,
 'worth': 849,
 "world's": 850,
 'gender': 851,
 'large': 852,
 'chance': 853,
 'dream': 854,
 'pain': 855,
 'older': 856,
 'judge': 857,
 'los': 858,
 'realize': 859,
 'cause': 860,
 '11': 861,
 'earth': 862,
 'super': 863,
 '8': 864,
 'freedom': 865,
 'stand': 866,
 'easier': 867,
 'treatment': 868,
 'beginning': 869,
 'creating': 870,
 'works': 871,
 'protect': 872,
 'couples': 873,
 'certain': 874,
 'certainly': 875,
 'seeing': 876,
 'force': 877,
 'press': 878,
 'actress': 879,
 'fire': 880,
 'either': 881,
 'challenges': 882,
 'planning': 883,
 'stars': 884,
 'co': 885,
 'lack': 886,
 'hotel': 887,
 '6': 888,
 'ahead': 889,
 'oil': 890,
 'secretary': 891,
 'effort': 892,
 'final': 893,
 'form': 894,
 'vacation': 895,
 'workers': 896,
 'accused': 897,
 'honor': 898,
 'follow': 899,
 'consider': 900,
 'difference': 901,
 'changes': 902,
 'low': 903,
 'reports': 904,
 'actor': 905,
 'moms': 906,
 'voters': 907,
 'published': 908,
 'problems': 909,
 'supreme': 910,
 'dinner': 911,
 'worry': 912,
 'please': 913,
 'rich': 914,
 'further': 915,
 'trump’s': 916,
 'groups': 917,
 'value': 918,
 'singer': 919,
 'released': 920,
 'performance': 921,
 'cases': 922,
 'looked': 923,
 'third': 924,
 'happened': 925,
 'monday': 926,
 'brain': 927,
 'wearing': 928,
 'expect': 929,
 'agree': 930,
 'eight': 931,
 'huge': 932,
 'higher': 933,
 'experiences': 934,
 'leader': 935,
 'town': 936,
 'results': 937,
 'apparently': 938,
 '100': 939,
 '2016': 940,
 'turns': 941,
 'comments': 942,
 'reportedly': 943,
 'foods': 944,
 'pick': 945,
 'plus': 946,
 'watching': 947,
 'choices': 948,
 'products': 949,
 'speak': 950,
 'return': 951,
 'include': 952,
 'm': 953,
 'message': 954,
 'greatest': 955,
 'weather': 956,
 'events': 957,
 'journey': 958,
 'worked': 959,
 'images': 960,
 'sports': 961,
 'movement': 962,
 "'": 963,
 'answer': 964,
 'continues': 965,
 'begin': 966,
 'similar': 967,
 'test': 968,
 'led': 969,
 'cool': 970,
 'plans': 971,
 'candidates': 972,
 'rules': 973,
 'calling': 974,
 'dr': 975,
 'investigation': 976,
 'quickly': 977,
 'due': 978,
 'cover': 979,
 'tough': 980,
 'c': 981,
 'goal': 982,
 'angeles': 983,
 '15': 984,
 'starting': 985,
 'student': 986,
 'earlier': 987,
 'games': 988,
 'bank': 989,
 'involved': 990,
 'wonder': 991,
 'guy': 992,
 'surprise': 993,
 'attacks': 994,
 'jobs': 995,
 'flight': 996,
 'access': 997,
 'joy': 998,
 'path': 999,
 '50': 1000,
 ...}

In [15]:
len(tokenizer.word_index)

29160

In [16]:
data=tokenizer.texts_to_sequences(data)

In [17]:
input_sequences=[]
for seq in data:
    if len(seq)<2:
        continue
    for i in range(1,len(seq)):
        ngram=seq[:i+1]
        input_sequences.append(ngram)

In [18]:
input_sequences

[[100, 4],
 [100, 4, 15073],
 [100, 4, 15073, 2933],
 [100, 4, 15073, 2933, 3],
 [100, 4, 15073, 2933, 3, 10747],
 [100, 4, 15073, 2933, 3, 10747, 639],
 [100, 4, 15073, 2933, 3, 10747, 639, 2],
 [100, 4, 15073, 2933, 3, 10747, 639, 2, 315],
 [100, 4, 15073, 2933, 3, 10747, 639, 2, 315, 7145],
 [100, 4, 15073, 2933, 3, 10747, 639, 2, 315, 7145, 539],
 [100, 4, 15073, 2933, 3, 10747, 639, 2, 315, 7145, 539, 13],
 [100, 4, 15073, 2933, 3, 10747, 639, 2, 315, 7145, 539, 13, 3],
 [100, 4, 15073, 2933, 3, 10747, 639, 2, 315, 7145, 539, 13, 3, 108],
 [100, 4, 15073, 2933, 3, 10747, 639, 2, 315, 7145, 539, 13, 3, 108, 4],
 [100, 4, 15073, 2933, 3, 10747, 639, 2, 315, 7145, 539, 13, 3, 108, 4, 1135],
 [100,
  4,
  15073,
  2933,
  3,
  10747,
  639,
  2,
  315,
  7145,
  539,
  13,
  3,
  108,
  4,
  1135,
  4905],
 [100,
  4,
  15073,
  2933,
  3,
  10747,
  639,
  2,
  315,
  7145,
  539,
  13,
  3,
  108,
  4,
  1135,
  4905,
  6],
 [100,
  4,
  15073,
  2933,
  3,
  10747,
  639,
  2,
  315,
  7145,
  539,
  13,
  3,
  108,
  4,
  1135,
  4905,
  6,
  15074],
 [100,
  4,
  15073,
  2933,
  3,
  10747,
  639,
  2,
  315,
  7145,
  539,
  13,
  3,
  108,
  4,
  1135,
  4905,
  6,
  15074,
  52],
 [100,
  4,
  15073,
  2933,
  3,
  10747,
  639,
  2,
  315,
  7145,
  539,
  13,
  3,
  108,
  4,
  1135,
  4905,
  6,
  15074,
  52,
  55],
 [100,
  4,
  15073,
  2933,
  3,
  10747,
  639,
  2,
  315,
  7145,
  539,
  13,
  3,
  108,
  4,
  1135,
  4905,
  6,
  15074,
  52,
  55,
  526],
 [100,
  4,
  15073,
  2933,
  3,
  10747,
  639,
  2,
  315,
  7145,
  539,
  13,
  3,
  108,
  4,
  1135,
  4905,
  6,
  15074,
  52,
  55,
  526,
  4906],
 [100,
  4,
  15073,
  2933,
  3,
  10747,
  639,
  2,
  315,
  7145,
  539,
  13,
  3,
  108,
  4,
  1135,
  4905,
  6,
  15074,
  52,
  55,
  526,
  4906,
  2],
 [509, 8],
 [509, 8, 1290],
 [509, 8, 1290, 315],
 [509, 8, 1290, 315, 1636],
 [509, 8, 1290, 315, 1636, 6],
 [509, 8, 1290, 315, 1636, 6, 2773],
 [509, 8, 1290, 315, 1636, 6, 2773, 71],
 [60, 8],
 [60, 8, 2],
 [60, 8, 2, 208],
 [60, 8, 2, 208, 2934],
 [60, 8, 2, 208, 2934, 40],
 [60, 8, 2, 208, 2934, 40, 14],
 [60, 8, 2, 208, 2934, 40, 14, 196],
 [60, 8, 2, 208, 2934, 40, 14, 196, 3],
 [60, 8, 2, 208, 2934, 40, 14, 196, 3, 566],
 [60, 8, 2, 208, 2934, 40, 14, 196, 3, 566, 4907],
 [60, 8, 2, 208, 2934, 40, 14, 196, 3, 566, 4907, 3],
 [60, 8, 2, 208, 2934, 40, 14, 196, 3, 566, 4907, 3, 1426],
 [60, 8, 2, 208, 2934, 40, 14, 196, 3, 566, 4907, 3, 1426, 4],
 [60, 8, 2, 208, 2934, 40, 14, 196, 3, 566, 4907, 3, 1426, 4, 8503],
 [60, 8, 2, 208, 2934, 40, 14, 196, 3, 566, 4907, 3, 1426, 4, 8503, 10748],
 [60,
  8,
  2,
  208,
  2934,
  40,
  14,
  196,
  3,
  566,
  4907,
  3,
  1426,
  4,
  8503,
  10748,
  2317],
 [60,
  8,
  2,
  208,
  2934,
  40,
  14,
  196,
  3,
  566,
  4907,
  3,
  1426,
  4,
  8503,
  10748,
  2317,
  340],
 [60,
  8,
  2,
  208,
  2934,
  40,
  14,
  196,
  3,
  566,
  4907,
  3,
  1426,
  4,
  8503,
  10748,
  2317,
  340,
  5],
 [60,
  8,
  2,
  208,
  2934,
  40,
  14,
  196,
  3,
  566,
  4907,
  3,
  1426,
  4,
  8503,
  10748,
  2317,
  340,
  5,
  218],
 [60,
  8,
  2,
  208,
  2934,
  40,
  14,
  196,
  3,
  566,
  4907,
  3,
  1426,
  4,
  8503,
  10748,
  2317,
  340,
  5,
  218,
  119],
 [60,
  8,
  2,
  208,
  2934,
  40,
  14,
  196,
  3,
  566,
  4907,
  3,
  1426,
  4,
  8503,
  10748,
  2317,
  340,
  5,
  218,
  119,
  43],
 [60,
  8,
  2,
  208,
  2934,
  40,
  14,
  196,
  3,
  566,
  4907,
  3,
  1426,
  4,
  8503,
  10748,
  2317,
  340,
  5,
  218,
  119,
  43,
  241],
 [60,
  8,
  2,
  208,
  2934,
  40,
  14,
  196,
  3,
  566,
  4907,
  3,
  1426,
  4,
  8503,
  10748,
  2317,
  340,
  5,
  218,
  119,
  43,
  241,
  2],
 [75, 4459],
 [75, 4459, 16],
 [75, 4459, 16, 2],
 [75, 4459, 16, 2, 1427],
 [75, 4459, 16, 2, 1427, 3],
 [75, 4459, 16, 2, 1427, 3, 420],
 [75, 4459, 16, 2, 1427, 3, 420, 55],
 [75, 4459, 16, 2, 1427, 3, 420, 55, 230],
 [75, 4459, 16, 2, 1427, 3, 420, 55, 230, 150],
 [75, 4459, 16, 2, 1427, 3, 420, 55, 230, 150, 8504],
 [75, 4459, 16, 2, 1427, 3, 420, 55, 230, 150, 8504, 62],
 [75, 4459, 16, 2, 1427, 3, 420, 55, 230, 150, 8504, 62, 309],
 [75, 4459, 16, 2, 1427, 3, 420, 55, 230, 150, 8504, 62, 309, 3],
 [75, 4459, 16, 2, 1427, 3, 420, 55, 230, 150, 8504, 62, 309, 3, 1189],
 [75, 4459, 16, 2, 1427, 3, 420, 55, 230, 150, 8504, 62, 309, 3, 1189, 2],
 [75,
  4459,
  16,
  2,
  1427,
  3,
  420,
  55,
  230,
  150,
  8504,
  62,
  309,
  3,
  1189,
  2,
  3297],
 [75,
  4459,
  16,
  2,
  1427,
  3,
  420,
  55,
  230,
  150,
  8504,
  62,
  309,
  3,
  1189,
  2,
  3297,
  9],
 [75,
  4459,
  16,
  2,
  1427,
  3,
  420,
  55,
  230,
  150,
  8504,
  62,
  309,
  3,
  1189,
  2,
  3297,
  9,
  2],
 [75,
  4459,
  16,
  2,
  1427,
  3,
  420,
  55,
  230,
  150,
  8504,
  62,
  309,
  3,
  1189,
  2,
  3297,
  9,
  2,
  193],
 [75,
  4459,
  16,
  2,
  1427,
  3,
  420,
  55,
  230,
  150,
  8504,
  62,
  309,
  3,
  1189,
  2,
  3297,
  9,
  2,
  193,
  374],
 [75,
  4459,
  16,
  2,
  1427,
  3,
  420,
  55,
  230,
  150,
  8504,
  62,
  309,
  3,
  1189,
  2,
  3297,
  9,
  2,
  193,
  374,
  3],
 [75,
  4459,
  16,
  2,
  1427,
  3,
  420,
  55,
  230,
  150,
  8504,
  62,
  309,
  3,
  1189,
  2,
  3297,
  9,
  2,
  193,
  374,
  3,
  4908],
 [100, 7146],
 [100, 7146, 16],
 [100, 7146, 16, 4909],
 [100, 7146, 16, 4909, 5434],
 [100, 7146, 16, 4909, 5434, 75],
 [100, 7146, 16, 4909, 5434, 75, 109],
 [100, 7146, 16, 4909, 5434, 75, 109, 2503],
 [100, 7146, 16, 4909, 5434, 75, 109, 2503, 552],
 [100, 7146, 16, 4909, 5434, 75, 109, 2503, 552, 4460],
 [100, 7146, 16, 4909, 5434, 75, 109, 2503, 552, 4460, 4],
 [100, 7146, 16, 4909, 5434, 75, 109, 2503, 552, 4460, 4, 608],
 [11, 171],
 [11, 171, 25],
 [11, 171, 25, 83],
 [11, 171, 25, 83, 3],
 [11, 171, 25, 83, 3, 149],
 [11, 171, 25, 83, 3, 149, 46],
 [11, 171, 25, 83, 3, 149, 46, 16],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435, 4910],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435, 4910, 40],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435, 4910, 40, 11],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435, 4910, 40, 11, 22],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435, 4910, 40, 11, 22, 3298],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435, 4910, 40, 11, 22, 3298, 3],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435, 4910, 40, 11, 22, 3298, 3, 2318],
 [11, 171, 25, 83, 3, 149, 46, 16, 5435, 4910, 40, 11, 22, 3298, 3, 2318, 4],
 [11,
  171,
  25,
  83,
  3,
  149,
  46,
  16,
  5435,
  4910,
  40,
  11,
  22,
  3298,
  3,
  2318,
  4,
  1637],
 [11,
  171,
  25,
  83,
  3,
  149,
  46,
  16,
  5435,
  4910,
  40,
  11,
  22,
  3298,
  3,
  2318,
  4,
  1637,
  16],
 [11,
  171,
  25,
  83,
  3,
  149,
  46,
  16,
  5435,
  4910,
  40,
  11,
  22,
  3298,
  3,
  2318,
  4,
  1637,
  16,
  55],
 [11,
  171,
  25,
  83,
  3,
  149,
  46,
  16,
  5435,
  4910,
  40,
  11,
  22,
  3298,
  3,
  2318,
  4,
  1637,
  16,
  55,
  107],
 [11,
  171,
  25,
  83,
  3,
  149,
  46,
  16,
  5435,
  4910,
  40,
  11,
  22,
  3298,
  3,
  2318,
  4,
  1637,
  16,
  55,
  107,
  584],
 [11,
  171,
  25,
  83,
  3,
  149,
  46,
  16,
  5435,
  4910,
  40,
  11,
  22,
  3298,
  3,
  2318,
  4,
  1637,
  16,
  55,
  107,
  584,
  510],
 [11,
  171,
  25,
  83,
  3,
  149,
  46,
  16,
  5435,
  4910,
  40,
  11,
  22,
  3298,
  3,
  2318,
  4,
  1637,
  16,
  55,
  107,
  584,
  510,
  11],
 [11,
  171,
  25,
  83,
  3,
  149,
  46,
  16,
  5435,
  4910,
  40,
  11,
  22,
  3298,
  3,
  2318,
  4,
  1637,
  16,
  55,
  107,
  584,
  510,
  11,
  7147],
 [2935, 15],
 [2935, 15, 331],
 [2935, 15, 331, 112],
 [2935, 15, 331, 112, 8505],
 [2935, 15, 331, 112, 8505, 6],
 [2935, 15, 331, 112, 8505, 6, 1291],
 [2935, 15, 331, 112, 8505, 6, 1291, 15],
 [2935, 15, 331, 112, 8505, 6, 1291, 15, 870],
 [2935, 15, 331, 112, 8505, 6, 1291, 15, 870, 41],
 [2935, 15, 331, 112, 8505, 6, 1291, 15, 870, 41, 148],
 [2935, 15, 331, 112, 8505, 6, 1291, 15, 870, 41, 148, 15075],
 [2935, 15, 331, 112, 8505, 6, 1291, 15, 870, 41, 148, 15075, 15076],
 [2935, 15, 331, 112, 8505, 6, 1291, 15, 870, 41, 148, 15075, 15076, 567],
 [2935, 15, 331, 112, 8505, 6, 1291, 15, 870, 41, 148, 15075, 15076, 567, 65],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39,
  5],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39,
  5,
  20],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39,
  5,
  20,
  42],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39,
  5,
  20,
  42,
  378],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39,
  5,
  20,
  42,
  378,
  31],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39,
  5,
  20,
  42,
  378,
  31,
  1467],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39,
  5,
  20,
  42,
  378,
  31,
  1467,
  620],
 [2935,
  15,
  331,
  112,
  8505,
  6,
  1291,
  15,
  870,
  41,
  148,
  15075,
  15076,
  567,
  65,
  782,
  1686,
  15077,
  19,
  96,
  88,
  3103,
  595,
  38,
  39,
  5,
  20,
  42,
  378,
  31,
  1467,
  620,
  3],
 [21, 8506],
 [21, 8506, 2214],
 [21, 8506, 2214, 16],
 [21, 8506, 2214, 16, 54],
 [21, 8506, 2214, 16, 54, 9],
 [21, 8506, 2214, 16, 54, 9, 215],
 [21, 8506, 2214, 16, 54, 9, 215, 7],
 [21, 8506, 2214, 16, 54, 9, 215, 7, 93],
 [21, 8506, 2214, 16, 54, 9, 215, 7, 93, 15078],
 [21, 8506, 2214, 16, 54, 9, 215, 7, 93, 15078, 1961],
 [21, 8506, 2214, 16, 54, 9, 215, 7, 93, 15078, 1961, 1292],
 [21, 8506, 2214, 16, 54, 9, 215, 7, 93, 15078, 1961, 1292, 21],
 [21, 8506, 2214, 16, 54, 9, 215, 7, 93, 15078, 1961, 1292, 21, 8506],
 [21, 8506, 2214, 16, 54, 9, 215, 7, 93, 15078, 1961, 1292, 21, 8506, 2214],
 [21,
  8506,
  2214,
  16,
  54,
  9,
  215,
  7,
  93,
  15078,
  1961,
  1292,
  21,
  8506,
  2214,
  16],
 [21,
  8506,
  2214,
  16,
  54,
  9,
  215,
  7,
  93,
  15078,
  1961,
  1292,
  21,
  8506,
  2214,
  16,
  54],
 [21,
  8506,
  2214,
  16,
  54,
  9,
  215,
  7,
  93,
  15078,
  1961,
  1292,
  21,
  8506,
  2214,
  16,
  54,
  45],
 [21,
  8506,
  2214,
  16,
  54,
  9,
  215,
  7,
  93,
  15078,
  1961,
  1292,
  21,
  8506,
  2214,
  16,
  54,
  45,
  215],
 [21,
  8506,
  2214,
  16,
  54,
  9,
  215,
  7,
  93,
  15078,
  1961,
  1292,
  21,
  8506,
  2214,
  16,
  54,
  45,
  215,
  106],
 [21,
  8506,
  2214,
  16,
  54,
  9,
  215,
  7,
  93,
  15078,
  1961,
  1292,
  21,
  8506,
  2214,
  16,
  54,
  45,
  215,
  106,
  8507],
 [21,
  8506,
  2214,
  16,
  54,
  9,
  215,
  7,
  93,
  15078,
  1961,
  1292,
  21,
  8506,
  2214,
  16,
  54,
  45,
  215,
  106,
  8507,
  248],
 [24, 316],
 [24, 316, 602],
 [24, 316, 602, 13],
 [24, 316, 602, 13, 2],
 [24, 316, 602, 13, 2, 701],
 [24, 316, 602, 13, 2, 701, 9],
 [24, 316, 602, 13, 2, 701, 9, 15],
 [24, 316, 602, 13, 2, 701, 9, 15, 3299],
 [24, 316, 602, 13, 2, 701, 9, 15, 3299, 3],
 [24, 316, 602, 13, 2, 701, 9, 15, 3299, 3, 2],
 [24, 316, 602, 13, 2, 701, 9, 15, 3299, 3, 2, 101],
 [24, 316, 602, 13, 2, 701, 9, 15, 3299, 3, 2, 101, 210],
 [24, 316, 602, 13, 2, 701, 9, 15, 3299, 3, 2, 101, 210, 183],
 [6, 4],
 [6, 4, 157],
 [6, 4, 157, 5],
 [6, 4, 157, 5, 2],
 [6, 4, 157, 5, 2, 93],
 [6, 4, 157, 5, 2, 93, 842],
 [6, 4, 157, 5, 2, 93, 842, 3523],
 [6, 4, 157, 5, 2, 93, 842, 3523, 559],
 [6, 4, 157, 5, 2, 93, 842, 3523, 559, 12],
 [6, 4, 157, 5, 2, 93, 842, 3523, 559, 12, 120],
 [6, 4, 157, 5, 2, 93, 842, 3523, 559, 12, 120, 86],
 [6, 4, 157, 5, 2, 93, 842, 3523, 559, 12, 120, 86, 33],
 [6, 4, 157, 5, 2, 93, 842, 3523, 559, 12, 120, 86, 33, 20],
 [6, 4, 157, 5, 2, 93, 842, 3523, 559, 12, 120, 86, 33, 20, 122],
 [2, 98],
 [2, 98, 1752],
 [2, 98, 1752, 13],
 [2, 98, 1752, 13, 509],
 [2, 98, 1752, 13, 509, 10749],
 [2, 98, 1752, 13, 509, 10749, 33],
 [2, 98, 1752, 13, 509, 10749, 33, 2],
 [2, 98, 1752, 13, 509, 10749, 33, 2, 4911],
 [2, 98, 1752, 13, 509, 10749, 33, 2, 4911, 293],
 [64, 36],
 [64, 36, 37],
 [64, 36, 37, 79],
 [64, 36, 37, 79, 12],
 [64, 36, 37, 79, 12, 177],
 [64, 36, 37, 79, 12, 177, 375],
 [64, 36, 37, 79, 12, 177, 375, 33],
 [64, 36, 37, 79, 12, 177, 375, 33, 283],
 [64, 36, 37, 79, 12, 177, 375, 33, 283, 17],
 [64, 36, 37, 79, 12, 177, 375, 33, 283, 17, 2],
 [64, 36, 37, 79, 12, 177, 375, 33, 283, 17, 2, 626],
 [64, 36, 37, 79, 12, 177, 375, 33, 283, 17, 2, 626, 539],
 [64, 36, 37, 79, 12, 177, 375, 33, 283, 17, 2, 626, 539, 205],
 [64, 36, 37, 79, 12, 177, 375, 33, 283, 17, 2, 626, 539, 205, 26],
 [64, 36, 37, 79, 12, 177, 375, 33, 283, 17, 2, 626, 539, 205, 26, 3300],
 [64, 36, 37, 79, 12, 177, 375, 33, 283, 17, 2, 626, 539, 205, 26, 3300, 23],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12,
  177],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12,
  177,
  167],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12,
  177,
  167,
  33],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12,
  177,
  167,
  33,
  283],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12,
  177,
  167,
  33,
  283,
  48],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12,
  177,
  167,
  33,
  283,
  48,
  12],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12,
  177,
  167,
  33,
  283,
  48,
  12,
  226],
 [64,
  36,
  37,
  79,
  12,
  177,
  375,
  33,
  283,
  17,
  2,
  626,
  539,
  205,
  26,
  3300,
  23,
  93,
  54,
  37,
  138,
  12,
  177,
  167,
  33,
  283,
  48,
  12,
  226,
  90],
 [590, 262],
 [590, 262, 14],
 [590, 262, 14, 68],
 [590, 262, 14, 68, 17],
 [590, 262, 14, 68, 17, 4],
 [590, 262, 14, 68, 17, 4, 8508],
 [590, 262, 14, 68, 17, 4, 8508, 447],
 [590, 262, 14, 68, 17, 4, 8508, 447, 5436],
 [590, 262, 14, 68, 17, 4, 8508, 447, 5436, 100],
 [590, 262, 14, 68, 17, 4, 8508, 447, 5436, 100, 2],
 [590, 262, 14, 68, 17, 4, 8508, 447, 5436, 100, 2, 15079],
 [590, 262, 14, 68, 17, 4, 8508, 447, 5436, 100, 2, 15079, 15080],
 [590, 262, 14, 68, 17, 4, 8508, 447, 5436, 100, 2, 15079, 15080, 961],
 [590, 262, 14, 68, 17, 4, 8508, 447, 5436, 100, 2, 15079, 15080, 961, 2387],
 [590,
  262,
  14,
  68,
  17,
  4,
  8508,
  447,
  5436,
  100,
  2,
  15079,
  15080,
  961,
  2387,
  6],
 [590,
  262,
  14,
  68,
  17,
  4,
  8508,
  447,
  5436,
  100,
  2,
  15079,
  15080,
  961,
  2387,
  6,
  2040],
 [590,
  262,
  14,
  68,
  17,
  4,
  8508,
  447,
  5436,
  100,
  2,
  15079,
  15080,
  961,
  2387,
  6,
  2040,
  15081],
 [590,
  262,
  14,
  68,
  17,
  4,
  8508,
  447,
  5436,
  100,
  2,
  15079,
  15080,
  961,
  2387,
  6,
  2040,
  15081,
  15],
 [590,
  262,
  14,
  68,
  17,
  4,
  8508,
  447,
  5436,
  100,
  2,
  15079,
  15080,
  961,
  2387,
  6,
  2040,
  15081,
  15,
  46],
 [11, 82],
 [11, 82, 21],
 [11, 82, 21, 627],
 [11, 82, 21, 627, 55],
 [11, 82, 21, 627, 55, 248],
 [11, 82, 21, 627, 55, 248, 3],
 [11, 82, 21, 627, 55, 248, 3, 4],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437, 3781],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437, 3781, 11],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437, 3781, 11, 22],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437, 3781, 11, 22, 57],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437, 3781, 11, 22, 57, 2774],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437, 3781, 11, 22, 57, 2774, 36],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437, 3781, 11, 22, 57, 2774, 36, 433],
 [11, 82, 21, 627, 55, 248, 3, 4, 5437, 3781, 11, 22, 57, 2774, 36, 433, 568],
 [11,
  82,
  21,
  627,
  55,
  248,
  3,
  4,
  5437,
  3781,
  11,
  22,
  57,
  2774,
  36,
  433,
  568,
  7],
 [11,
  82,
  21,
  627,
  55,
  248,
  3,
  4,
  5437,
  3781,
  11,
  22,
  57,
  2774,
  36,
  433,
  568,
  7,
  4],
 [11,
  82,
  21,
  627,
  55,
  248,
  3,
  4,
  5437,
  3781,
  11,
  22,
  57,
  2774,
  36,
  433,
  568,
  7,
  4,
  735],
 [11,
  82,
  21,
  627,
  55,
  248,
  3,
  4,
  5437,
  3781,
  11,
  22,
  57,
  2774,
  36,
  433,
  568,
  7,
  4,
  735,
  670],
 [11,
  82,
  21,
  627,
  55,
  248,
  3,
  4,
  5437,
  3781,
  11,
  22,
  57,
  2774,
  36,
  433,
  568,
  7,
  4,
  735,
  670,
  381],
 [11,
  82,
  21,
  627,
  55,
  248,
  3,
  4,
  5437,
  3781,
  11,
  22,
  57,
  2774,
  36,
  433,
  568,
  7,
  4,
  735,
  670,
  381,
  33],
 [11,
  82,
  21,
  627,
  55,
  248,
  3,
  4,
  5437,
  3781,
  11,
  22,
  57,
  2774,
  36,
  433,
  568,
  7,
  4,
  735,
  670,
  381,
  33,
  55],
 [11,
  82,
  21,
  627,
  55,
  248,
  3,
  4,
  5437,
  3781,
  11,
  22,
  57,
  2774,
  36,
  433,
  568,
  7,
  4,
  735,
  670,
  381,
  33,
  55,
  736],
 [72, 609],
 [72, 609, 10],
 [72, 609, 10, 59],
 [72, 609, 10, 59, 456],
 [72, 609, 10, 59, 456, 2388],
 [72, 609, 10, 59, 456, 2388, 3104],

# Padding Implementation

In [19]:
max_len = max([len(i) for i in input_sequences])

In [20]:
max_len

185

In [21]:
input = pad_sequences(input_sequences, padding='pre',maxlen=max_len)

In [22]:
X=input[:,:-1]
y=input[:,-1]

In [23]:
X.shape

(376600, 184)

In [24]:
y.shape

(376600,)

In [25]:
y= np.array(y)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [28]:
X_train.shape

(301280, 184)

In [29]:
vocab_size = len(tokenizer.word_index)+1

In [30]:
vocab_size

29161

In [31]:
max_len=X.shape[1]

In [32]:
model= Sequential([Embedding(vocab_size,128,input_length=max_len),
                   LSTM(256),
                   Dense(vocab_size, activation='softmax')])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [33]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [34]:
model.build(input_shape=(None,max_len))

In [35]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 184, 128)       │     3,732,608 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 29161)          │     7,494,377 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,621,225 (44.33 MB)

 Trainable params: 11,621,225 (44.33 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train,y_train, epochs=30,validation_data=(X_test,y_test))

Epoch 1/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 255s 26ms/step - accuracy: 0.0891 - loss: 7.1387 - val_accuracy: 0.1165 - val_loss: 6.7745
Epoch 2/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 229s 24ms/step - accuracy: 0.1276 - loss: 6.3641 - val_accuracy: 0.1295 - val_loss: 6.6739
Epoch 3/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 229s 24ms/step - accuracy: 0.1496 - loss: 5.8919 - val_accuracy: 0.1351 - val_loss: 6.7137
Epoch 4/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 262s 24ms/step - accuracy: 0.1709 - loss: 5.4197 - val_accuracy: 0.1333 - val_loss: 6.8346
Epoch 5/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.1980 - loss: 4.9285 - val_accuracy: 0.1328 - val_loss: 7.0023
Epoch 6/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.2341 - loss: 4.4565 - val_accuracy: 0.1282 - val_loss: 7.1972
Epoch 7/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.2782 - loss: 4.0282 - val_accuracy: 0.1222 - val_loss: 7.4183
Epoch 8/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 279s 26ms/step - accuracy: 0.3215 - loss: 3.6557 - val_accuracy: 0.1178 - val_loss: 7.5944
Epoch 9/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 229s 24ms/step - accuracy: 0.3647 - loss: 3.3401 - val_accuracy: 0.1163 - val_loss: 7.7956
Epoch 10/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 262s 24ms/step - accuracy: 0.4030 - loss: 3.0709 - val_accuracy: 0.1117 - val_loss: 7.9617
Epoch 11/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 229s 24ms/step - accuracy: 0.4367 - loss: 2.8460 - val_accuracy: 0.1071 - val_loss: 8.1330
Epoch 12/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 229s 24ms/step - accuracy: 0.4669 - loss: 2.6528 - val_accuracy: 0.1043 - val_loss: 8.3097
Epoch 13/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.4937 - loss: 2.4892 - val_accuracy: 0.1034 - val_loss: 8.4799
Epoch 14/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.5167 - loss: 2.3539 - val_accuracy: 0.1019 - val_loss: 8.6319
Epoch 15/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.5345 - loss: 2.2438 - val_accuracy: 0.0996 - val_loss: 8.7732
Epoch 16/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.5499 - loss: 2.1463 - val_accuracy: 0.1002 - val_loss: 8.8706
Epoch 17/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.5653 - loss: 2.0593 - val_accuracy: 0.0984 - val_loss: 8.9982
Epoch 18/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 229s 24ms/step - accuracy: 0.5769 - loss: 1.9888 - val_accuracy: 0.0959 - val_loss: 9.1087
Epoch 19/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 228s 24ms/step - accuracy: 0.5905 - loss: 1.9180 - val_accuracy: 0.0966 - val_loss: 9.2022
Epoch 20/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 229s 24ms/step - accuracy: 0.5984 - loss: 1.8613 - val_accuracy: 0.0957 - val_loss: 9.3033
Epoch 21/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 230s 24ms/step - accuracy: 0.6083 - loss: 1.8070 - val_accuracy: 0.0967 - val_loss: 9.3985
Epoch 22/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 229s 24ms/step - accuracy: 0.6157 - loss: 1.7634 - val_accuracy: 0.0932 - val_loss: 9.4764
Epoch 23/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 233s 25ms/step - accuracy: 0.6212 - loss: 1.7271 - val_accuracy: 0.0954 - val_loss: 9.5395
Epoch 24/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 233s 25ms/step - accuracy: 0.6281 - loss: 1.6878 - val_accuracy: 0.0935 - val_loss: 9.6230
Epoch 25/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 250s 27ms/step - accuracy: 0.6332 - loss: 1.6597 - val_accuracy: 0.0919 - val_loss: 9.6990
Epoch 26/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 234s 25ms/step - accuracy: 0.6392 - loss: 1.6281 - val_accuracy: 0.0928 - val_loss: 9.7808
Epoch 27/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 234s 25ms/step - accuracy: 0.6420 - loss: 1.6045 - val_accuracy: 0.0916 - val_loss: 9.8243
Epoch 28/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 234s 25ms/step - accuracy: 0.6456 - loss: 1.5830 - val_accuracy: 0.0900 - val_loss: 9.9105
Epoch 29/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 233s 25ms/step - accuracy: 0.6485 - loss: 1.5659 - val_accuracy: 0.0925 - val_loss: 9.9448
Epoch 30/30
9415/9415 ━━━━━━━━━━━━━━━━━━━━ 262s 25ms/step - accuracy: 0.6491 - loss: 1.5552 - val_accuracy: 0.0917 - val_loss: 9.9853

In [39]:
model.save('nextword_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [40]:
import pickle
with open ('tokenizer.pickle','wb') as file:
    pickle.dump(tokenizer,file)